image: ghcr.io/dbt-labs/snowflake:latest
tasks:
  - command: mkdir -p /workspace/.dbt && ln -snf /workspace/.dbt ~/.dbt
ports:
  - port: 8000
    onOpen: open-browser
  - port: 8081
    onOpen: open-preview
